package:
  name: resonate
  version: "1.1"

source:
  git_rev: master
  git_url: https://github.com/ocean-tracking-network/resonATe

build:
  number: 0
  noarch: python

python:
  - 3.8
  - 3.9
  - 3.10
  - 3.11

requirements:
  build:
    - python >=2.7
    - setuptools
    - pandas
    - numpy
    - sphinx
    - geopy
    - nose
    - colorama
    - plotly
    - nbconvert
  run:
    - python >=2.7
    - setuptools
    - pandas
    - numpy
    - sphinx
    - geopy
    - nose
    - colorama
    - plotly
    - nbconvert
test:
  imports:
    - resonate

about:
  home: https://github.com/ocean-tracking-network/resonATe
  license: GPL-2.0-only
  license_file: LICENSE
