package:
  name: resonate
  version: "1.0.9"

source:
  git_rev: master
  git_url: https://gitlab.oceantrack.org/otndc/resonate

build:
  number: 0
  noarch: python

requirements:
  build:
    - python {{ python }}
    - setuptools
    - pandas
    - numpy
    - sphinx
    - geopy
    - nose
    - colorama
    - plotly
    - nbconvert
  run:
    - python {{ python }}
    - setuptools
    - pandas
    - numpy
    - sphinx
    - geopy
    - nose
    - colorama
    - plotly
    - nbconvert
test:
  imports:
    - resonate

about:
  home: https://gitlab.oceantrack.org/otndc/resonate
  license: GPL
  license_file: LICENSE
