package:
  name: resonate
  version: "0.2.2"

source:
  git_rev: master
  git_url: https://gitlab.oceantrack.org/otndc/resonate

requirements:
  build:
    - python
    - setuptools
    - pandas
    - numpy
    - sphinx
    - geopy
    - simplejson
    - nose
    - colorama
    - folium
    - matplotlib
    - nbconvert
  run:
    - python
    - setuptools
    - pandas
    - numpy
    - sphinx
    - geopy
    - simplejson
    - nose
    - colorama
    - folium
    - matplotlib
    - nbconvert
test:
  imports:
    - resonate

about:
  home: https://gitlab.oceantrack.org/otndc/resonate
  license: GPL
  license_file: LICENSE
